# Generated by Django 3.2.9 on 2021-11-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Anon', max_length=20)),
                ('review', models.TextField(default='No review')),
                ('sentiment', models.CharField(default='None', max_length=20)),
            ],
        ),
    ]
