# Generated by Django 3.2.9 on 2021-11-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereviews',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
