# Generated by Django 3.2.9 on 2021-11-21 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_moviereviews_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereviews',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
