# Generated by Django 3.2.9 on 2021-12-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_moviereviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereviews',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
