# Generated by Django 3.2.9 on 2021-12-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_moviereviews_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereviews',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
